# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9001
    hooks: 
    #-   id: style-files
    #    args: [--style_pkg=styler, --style_fun=tidyverse_style]    
    -   id: roxygenize
        # roxygen requires loading pkg -> add dependencies from DESCRIPTION
        additional_dependencies:
        -    rvest
        -    httr
        -    dplyr
        -    purrr
        -    rlang
        -    utils
        -    cli 
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: no-debug-statement
    #-   id: deps-in-desc  
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks: 
    -   id: no-commit-to-branch
        args: [ --branch, master, --branch, develop] 
    -   id: check-added-large-files
        args: ['--maxkb=650']
    -   id: file-contents-sorter
        files: '^(\.Rbuildignore|\.gitignore)$'
    -   id: end-of-file-fixer
        exclude: '\.Rd'
    -   id: check-merge-conflict
    -   id: detect-private-key
-   repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.5.1
    hooks:
    # Only reuiqred when https://pre-commit.ci is used for config validation
    -   id: check-pre-commit-ci-config
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.(Rhistory|RData|Rds|rds)$'
        # `exclude: <regex>` to allow committing specific files
    -   id: banned-words
        name: Banned Words
        entry: ./.hooks/banned-words.sh
        language: script
    -   id: optipng
        name: Optimize PNGs
        entry: ./.hooks/optipng.sh
        language: script
        types: [png]

ci:
    autoupdate_schedule: monthly
